/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_native_embedding_ExecutionEventConsumer */

#ifndef _Included_org_example_native_embedding_ExecutionEventConsumer
#define _Included_org_example_native_embedding_ExecutionEventConsumer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_native_embedding_ExecutionEventConsumer
 * Method:    consumeExecutionEvent
 * Signature: (Lorg/graalvm/polyglot/management/ExecutionEvent;J)V
 */
JNIEXPORT void JNICALL Java_org_example_native_1embedding_ExecutionEventConsumer_consumeExecutionEvent
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
